name: 'Quality Monitor'

on:
  pull_request:
    branches: [ master ]

jobs:
  monitor-project-quality:
    name: Run the quality monitor
    runs-on: ubuntu-latest
    steps:
      - name: Detect pull request
        uses: jwalton/gh-find-current-pr@v1
        id: pr

      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@v3
        with:
          pr-number: ${{ steps.pr.outputs.number }}
          comments-strategy: UPDATE