name: Quality Monitor

on:
  pull_request:
    branches: [ master ]

jobs:
  monitor-project-quality:
    name: Run the quality monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: pr

      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@v3
        with:
          pr-number: ${{ steps.pr.outputs.number }}
          comments-strategy: UPDATE
          quality-gates: >
                {
                  "qualityGates": [
                    {
                      "metric": "line",
                      "threshold": 80.0,
                      "criticality": "FAILURE"
                    },
                    {
                      "metric": "checkstyle",
                      "threshold": 70.0,
                      "criticality": "UNSTABLE"
                    }
                  ]
                }  