name: Quality Monitor

on:
  pull_request:
    branches: [ master ]

jobs:
  monitor-project-quality:
    name: Run the quality monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "bug,feature,enhancement,breaking,tests,documentation,internal,dependencies"
          message: "Maintainer needs to assign at least one label before merge"

      - name: Detect Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: pr
      

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go Tests with Coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out > coverage.txt

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Run golangci-lint
        run: |
          golangci-lint run --out-format checkstyle > checkstyle-result.xml || true

      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@v3
        with:
          pr-number: ${{ steps.pr.outputs.number }}
          comments-strategy: UPDATE
          report-files: |
            coverage.txt
            checkstyle-result.xml
          quality-gates: >
                {
                  "qualityGates": [
                    {
                      "metric": "line",
                      "threshold": 80.0,
                      "criticality": "FAILURE"
                    },
                    {
                      "metric": "checkstyle",
                      "threshold": 70.0,
                      "criticality": "UNSTABLE"
                    }
                  ]
                }